dh1= Object.create(Movie);
dh1.setTitle("Die Hard 1");
MovieObserver.subscribe("play",PlayHandler);
MovieObserver.subscribe("stop",StopHandler);
dh1.play();
dh1.stop();
dh1.setCast(["Bruce Willis","Inti Piolanti","Jessica Alba"]);
console.log("Die Hard 1 Cast:");
console.log(dh1.getCast());
var bruce=new Actor("Bruce Willis","56");
var inti= new Actor("Inti Piolant","21");
console.log("Name of an Actor:");
console.log(bruce.getName());
console.log("Biography of an undiscovered actor:");
inti.setBiography("Born, live in the middle, not dead yet");
console.log(inti.getBiography());
